# -*- mode: ruby -*-
# vi: set ft=ruby :

DESIRED_VERSION = '2.4.1'

Vagrant.configure(2) do |config|
  # More boxes at https://atlas.hashicorp.com/search
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "private_network", ip: "10.10.10.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "TTPS-Ruby"
    vb.gui = false
    vb.memory = "512"
  end

  # Provision the box with a shell script. This installs rbenv + ruby-build and Ruby (+ dependencies).
  user = 'vagrant'
  home = "/home/#{user}"
  rbenv_path = "#{home}/.rbenv"
  profile_path = "#{home}/.bashrc"
  ruby_version = DESIRED_VERSION
  rbenv_abs_path = "#{rbenv_path}/bin/rbenv"
  gem_abs_path = "#{rbenv_path}/shims/gem"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git autoconf bison build-essential lib{ssl,yaml,sqlite3}-dev libreadline6{,-dev} zlib1g{,-dev}
    if [ ! -d #{rbenv_path} ]; then
      git clone https://github.com/sstephenson/rbenv.git #{rbenv_path}
      cd #{rbenv_path} && src/configure && make -C src
      git clone https://github.com/sstephenson/ruby-build.git #{rbenv_path}/plugins/ruby-build
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> #{profile_path}
      echo 'eval "$(rbenv init -)"' >> #{profile_path}
    else
      cd #{rbenv_path} && git pull origin master
      cd #{rbenv_path}/plugins/ruby-build && git pull origin master
    fi
    chown -R #{user}:#{user} #{rbenv_path}
    sudo -i -H -u #{user} /bin/bash -lc '#{rbenv_abs_path} install -s #{ruby_version} && #{rbenv_abs_path} global #{ruby_version} && #{gem_abs_path} update --system && #{gem_abs_path} install bundler'
  SHELL
end
